language: node_js

cache:
  directories:
    - node_modules

notifications:
  email: false

node_js:
  - 'node'
  - '7'
  - '6'
  - '4'

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install nasm -y

after_success:
  - npm run semantic-release

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
